set(USE_SDL2 OFF)
SET(PPU_Y 2)

set(PATH_DEFAULT \"/media\")
set(FILE_SYSTEM \"/dev/mmcblk0p2\")

set(CMDR_KEY_UP SDLK_UP) # Up
set(CMDR_KEY_RIGHT SDLK_RIGHT) # Right
set(CMDR_KEY_DOWN SDLK_DOWN) # Down
set(CMDR_KEY_LEFT SDLK_LEFT) # Left

set(CMDR_KEY_SYSTEM SDLK_LSHIFT) # Y
set(CMDR_KEY_PAGEUP SDLK_TAB) # L
set(CMDR_KEY_PAGEDOWN SDLK_BACKSPACE) # R
set(CMDR_KEY_OPEN SDLK_LCTRL) # A
set(CMDR_KEY_PARENT SDLK_LALT) # B
set(CMDR_KEY_OPERATION SDLK_SPACE) # X
set(CMDR_KEY_SELECT SDLK_ESCAPE) # SELECT
set(CMDR_KEY_TRANSFER SDLK_RETURN) # START

set(OSK_KEY_SYSTEM_IS_BACKSPACE ON)
