set(PPU_Y 2)
set(AUTOSCALE 1)
set(FILE_SYSTEM \"/dev/mmcblk1p1\")
set(PATH_DEFAULT getenv\(\"HOME\"\))
set(PATH_DEFAULT_RIGHT \"/media/mmcblk1p1\")
set(PATH_DEFAULT_RIGHT_FALLBACK \"/home/retrofw\")

set(MYKEY_UP SDLK_UP) # Up
set(MYKEY_RIGHT SDLK_RIGHT) # Right
set(MYKEY_DOWN SDLK_DOWN) # Down
set(MYKEY_LEFT SDLK_LEFT) # Left
set(MYKEY_SYSTEM SDLK_LSHIFT) # Y
set(MYKEY_PAGEUP SDLK_TAB) # L
set(MYKEY_PAGEDOWN SDLK_BACKSPACE) # R
set(MYKEY_OPEN SDLK_LCTRL) # A
set(MYKEY_PARENT SDLK_LALT) # B
set(MYKEY_OPERATION SDLK_SPACE) # X
set(MYKEY_SELECT SDLK_ESCAPE) # SELECT
set(MYKEY_TRANSFER SDLK_RETURN) # START
