set(USE_SDL2 OFF)
set(PATH_DEFAULT \"/media/sdcard\")

set(MYKEY_UP SDLK_UP) # Up
set(MYKEY_RIGHT SDLK_RIGHT) # Right
set(MYKEY_DOWN SDLK_DOWN) # Down
set(MYKEY_LEFT SDLK_LEFT) # Left

set(MYKEY_SYSTEM SDLK_TAB) # L
set(MYKEY_OPEN SDLK_LCTRL) # A
set(MYKEY_PARENT SDLK_LALT) # B
set(MYKEY_OPERATION SDLK_BACKSPACE) # R
set(MYKEY_SELECT SDLK_ESCAPE) # SELECT
set(MYKEY_TRANSFER SDLK_RETURN) # START

# Nothing to map MYKEY_PAGEUP and MYKEY_PAGEDOWN on RS-90

set(OSK_KEY_SYSTEM_IS_BACKSPACE ON)
